### ISSUE TITLE
Importing plotdevice takes >10 seconds

### ISSUE THREAD

**Issue by kstolzenberg** [plotdevice/plotdevice#26]
Importing plotdevice as a module seems to take an unusually long time:

```python
import time
start = time.time()

import plotdevice

print "time to import: %g" % (time.time()-start)
```

```
$ python test.py
time to import: 15.042
```

Is something up, or is this expected behavior? Thanks.

**Comment by samizdatco** [comment]
Is it safe to assume you're seeing this while running Yosemite and using the PyPI version of the module? If so then this is typical (albeit unfortunate). Between 10.9 and 10.10, Apple upgraded the PyObjC bundled with the system to a version with *serious* performance regressions when it comes to imports.

Since the last official release, I've been working on bundling a more up-to-date PyObjC as part of the `plotdevice` module and in my testing this has decreased load times significantly. If you get a chance to try installing the module from this repo (rather than PyPI) I'd love to hear whether it brings that 15(!) second number down a bit...

**Comment by kstolzenberg** [comment]
Yes - I had been using Yosemite and the PyPI version. Using the Github module worked brilliantly! Time to execute went from 15 seconds ---> 2-3 seconds. Thanks!
